### ISSUE TITLE
How can I hide the code folding gutter?

### ISSUE THREAD

**Issue by aguynamedben** [MaximSokolov/toggle-gutter#3]
I'd like:
* git gutter
* linter gutter
* NO code folding gutter! (i.e. hide it)

Is this possible using toggle-gutter? I don't see an easy way to hide the code folding gutter. I've hacked around the CSS a bit but it's not straightforward.

Bonus feature: it'd be cool if I could make the gutter very narrow... they're so wide by default!

**Comment by MaximSokolov** [comment]
This is not supported. I guess the easiest way is
```css
.icon-right::before {
  display: none !important;
}
```
> it'd be cool if I could make the gutter very narrow... they're so wide by default

You can make `line-number` gutter a bit smaller, still there a lot of extra space remains
```css
.line-number {
  padding-left: 0px !important;
}
```
